//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sem3Final.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cadidate
    {
        public int id { get; set; }
        public Nullable<int> id_member { get; set; }
        public Nullable<int> id_vacancy { get; set; }
        public string concern_person { get; set; }
        public Nullable<int> status { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> score { get; set; }
        public string answer_of_cadidate { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string submit_cadidate_cadidate { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Vacancy Vacancy { get; set; }
    }
}
