//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sem3Final.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbSem3Entities : DbContext
    {
        public dbSem3Entities()
            : base("name=dbSem3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Cadidate> Cadidates { get; set; }
        public virtual DbSet<CategoryOfQuestion> CategoryOfQuestions { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Examination> Examinations { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<QuestionOfExamination> QuestionOfExaminations { get; set; }
        public virtual DbSet<Vacancy> Vacancies { get; set; }
    }
}
